---
title: "DATA607 Final Project"
author: "Henry Otuadinma"
date: "17 March 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(xml2)
library(rvest)
library(extrafont)
library(ggraph)
library(ggridges)
library(pdftools)
library(tidyverse)
library(tidytext)
library(forcats)
library(reshape2)
library(tidyr)
library(igraph)
library(widyr)
library(viridis)
library(dplyr)
```


```{r}

  # list of reports, comments indicate important events around release of report
reportLinks=c("https://www.federalreserve.gov/monetarypolicy/files/20180713_mprfullreport.pdf",  
            "https://www.federalreserve.gov/monetarypolicy/files/20170707_mprfullreport.pdf",
            "https://www.federalreserve.gov/monetarypolicy/files/20160621_mprfullreport.pdf",            # released in jun, will label it July
            "https://www.federalreserve.gov/monetarypolicy/files/20150715_mprfullreport.pdf",            # July 2015  ( before lift off)
            "https://www.federalreserve.gov/monetarypolicy/files/20140715_mprfullreport.pdf",
            "https://www.federalreserve.gov/monetarypolicy/files/20130717_mprfullreport.pdf",            # July 2013  ( after Taper Tantrum)
            "https://www.federalreserve.gov/monetarypolicy/files/20120717_mprfullreport.pdf",
            "https://www.federalreserve.gov/monetarypolicy/files/20110713_mprfullreport.pdf",            # July 2011  ( early recovery)
            "https://www.federalreserve.gov/monetarypolicy/files/20100721_mprfullreport.pdf",
            "https://www.federalreserve.gov/monetarypolicy/files/20090721_mprfullreport.pdf",            # July 2009  ( end of Great Recession)
            "https://www.federalreserve.gov/monetarypolicy/files/20080715_mprfullreport.pdf",
            "https://www.federalreserve.gov/monetarypolicy/files/20070718_mprfullreport.pdf" ,           # July 2007  ( eve of  Great Recession)
            "https://www.federalreserve.gov/boarddocs/hh/2006/july/fullreport.pdf",
            "https://www.federalreserve.gov/boarddocs/hh/2005/july/fullreport.pdf",                      # July 2005  ( housing boom)
            "https://www.federalreserve.gov/boarddocs/hh/2004/july/fullreport.pdf",
            "https://www.federalreserve.gov/boarddocs/hh/2003/july/FullReport.pdf" ,                     # July 2003  ( deflation fears)
            "https://www.federalreserve.gov/boarddocs/hh/2002/july/FullReport.pdf",
            "https://www.federalreserve.gov/boarddocs/hh/2001/july/FullReport.pdf",                      # July 2001  ( dot come Recession)
            "https://www.federalreserve.gov/boarddocs/hh/2000/July/FullReport.pdf",
            "https://www.federalreserve.gov/boarddocs/hh/1999/July/FullReport.pdf",                      # July 1999  ( eve of dotcom Recession)
            "https://www.federalreserve.gov/boarddocs/hh/1998/july/FullReport.pdf",
            "https://www.federalreserve.gov/boarddocs/hh/1997/july/FullReport.pdf",                       # July 1997 ( irrational exhuberance)
            "https://www.federalreserve.gov/boarddocs/hh/1996/july/FullReport.pdf"
            )

```


```{r eval=FALSE}

fed_reports <- map(reportLinks,pdf_text)

```


```{r eval=FALSE}

length(fed_reports)

```


```{r eval=FALSE}
fed <- data.frame(report=c("Jul-2018",paste0("Jul-",seq(2017,1996,-1))),stringsAsFactors = FALSE) %>%
  mutate(text= fed_reports) %>% unnest(text) %>% 
  group_by(report) %>% mutate(page=row_number()) %>%
  ungroup() %>% mutate(text=strsplit(text,"\r")) %>% unnest(text) %>% mutate(text=gsub("\n","",text)) %>%
  group_by(report) %>% mutate(line=row_number())

```


```{r eval=FALSE}

write.csv(fed, "fed_reports.csv")

```


```{r}

fed_r <- read.csv("fed_reports.csv", stringsAsFactors=FALSE)

```


```{r}

head(fed_r)

```


```{r}

fed_x <- fed_r %>% dplyr::select(report, page, text, line)

```

```{r}
head(fed_x)

```


```{r}
words <- fed_x %>%
  unnest_tokens(word, text) %>%
  count(report, word, sort = TRUE) %>%
  ungroup()
```


```{r}
total_words <- words %>% 
  group_by(report) %>% 
  summarize(total = sum(n))

```

##### Comparing words count in each report

```{r}

ggplot(data=total_words, aes(x=seq(1996,2018),y=total))+
  geom_line(color="#27408b")+
  geom_point(shape=21,fill="white",color="#27408b",size=3,stroke=1.1)+
  scale_y_continuous(labels=scales::comma)+
  theme_ridges()+
  labs(x="year",y="Words count",
       title="Words count in Federal Reserve Monetary Policy Reports",
       subtitle="For July of each year 1996-2018")

```

##### Making a list of the most frequently occuring words in each report, while removing stop-words, numbers, and special characters

```{r}

fed_text <- fed_x %>% unnest_tokens(word,text)

```


```{r}
head(fed_text)
```
 
```{r}

fedText <- fed_text %>% 
  mutate(word = gsub("[^A-Za-z ]","",word)) %>% 
  filter(word != "") %>%
  anti_join(stop_words) %>%
  group_by(report) %>%
  count(word,sort=TRUE) %>% 
  mutate(rank=row_number()) %>%
  ungroup() %>% 
  arrange(rank,report) %>%
  filter(rank<11)
  

```

```{r}
head(fedText)
```


```{r}
tail(fedText)
```

##### Stop-words are gone

```{r}
p <- ggplot(fedText, aes(y=n,x=fct_reorder(word,n))) +
  geom_col(fill="#27408b")+
  facet_wrap(~report, scales= "free_y", ncol=5)+
  coord_flip()+
  theme_ridges(font_size=8.3)+
  labs(x="",y="",
       title="Most Frequent Words Federal Reserve Monetary Policy Report")

p

```

















